name: heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: npm install
        run: |
          npm install

      - name: npm build
        run: npm build

      - name: Add heroku remote
      if: ${{success()}}
      run: |
        echo Success
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      - name: Deploy to heroku
      run: |
        git push heroku HEAD:main -f